name: Android CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
      TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    
    # Set up JDK 8 which is compatible with Gradle 4.4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease

    # Zip the build folder
    - name: Zip build folder
      run: zip -r build.zip ./app/build

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ProtoHax-build-${{ github.sha }}
        path: build.zip
